eshop/eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    # path('test_products_route/', include('products.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop/products/urls.py
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [
    # path('', views.index, name='index'),
     path('<int:product_id>', views.detail, name='product-details'),
     path('product/<int:category_id>', views.filter_by_category, name='product-filter'),
     path('search', views.filter_by, name='product-fil')
    # path('', views.index, name='index'),
]

eshop/eshop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Hello this eshop</h1>
    <div>
        <a href="{% url 'products:index'  %}"> Home  </a>
        <a href="#"> About Us </a>
        <a href="#"> FAQ </a>
        <a href="#"> Contacts </a>
    </div>
    <div>
         {% for c in categories %}
        <a href="{% url 'products:product-filter' c.id %}"> {{ c.title }}  </a>
        {% endfor %}

        {% load mptt_tags %}
<ul>
    {% recursetree categories %}
        <li>
            {{ node.name }}
            <a href="{% url 'products:product-filter' node.id %}"> {{ node.name}}  </a>
            {% if not node.is_leaf_node %}
                <ul class="children">
                    {{ children }}

                </ul>
            {% endif %}
        </li>
    {% endrecursetree %}
</ul>

    </div>
    <div>
        {% block content %}
        {% endblock %}
    </div>
 <h1> footer maybe</h1>
</body>
</html>