eshop/eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    # path('test_products_route/', include('products.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eshop/frontend/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.home, name='search_filter'),
    path('faq/', views.faq, name='faq'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('cart/', views.cart, name='cart'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.sign_out, name='signout'),
    path('products/<int:product_id>', views.product_info, name='product-view'),
    path('products/filter/<int:category_id>',
         views.filter_by_category, name='product-filter'),
    path('filter/', views.filter_by_props, name='filter_props')
]

eshop/products/urls.py
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [
    # path('', views.index, name='index'),
     path('<int:product_id>', views.detail, name='product-details'),
     path('product/<int:category_id>', views.filter_by_category, name='product-filter'),
     path('search', views.filter_by, name='product-fil')
    # path('', views.index, name='index'),
]

eshop/products/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
# Create your models here.


class Category (MPTTModel):
    name = models.CharField(max_length=50)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        parent = ""
        if(self.parent is not None):
             parent = self.parent

        return '%s / %s' % (parent, self.name)



class Measurement(models.Model):
    unit = models.CharField(max_length=50, blank=True)
    value = models.FloatField()

    def __str__(self):
        return '%s %s' % (self.value, self.unit)


class Product(models.Model):
    title = models.CharField(max_length=30)
    price = models.DecimalField(decimal_places=2, max_digits=7, default=0)
    productCode = models.CharField(max_length=30, default="")
    categories = models.ForeignKey(Category, default=1, blank=True, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class Property(models.Model):
    name = models.CharField(max_length=60)
    #measurement = models.ForeignKey(Measurement, null=True, blank=True, on_delete= models.SET_NULL)
    description = models.CharField(max_length=1000, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


def upload_path_handler(instance, filename):
    return "product_{id}/{file}".format(id=instance.product.id, file=filename)


class ProductImage(models.Model):
    product = models.ForeignKey(Product, null=True, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=  upload_path_handler)

    def __str__(self):
        return self.image.url

eshop/frontend/views.py
from django.shortcuts import render, HttpResponse, redirect
from products import views as product_helpers
from cart import views as cart_helpers
from django.core.paginator import Paginator
from products.models import Property
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

from frontend.validators import len_validator, password_validator, unique_validator
import math

# Create your views here.


def home(request, products=None, message=None):
    term = request.POST.get('term')

    if not products:
        products = product_helpers.get_products(request)


    if term:
        term = request.POST.get('term')
        products = product_helpers.search_products((term))


    if term and len(products) > 0:
        paginator = Paginator(products, len(products))
    else:
        paginator = Paginator(products, 9)


    page = request.GET.get('page')
    products = paginator.get_page(page)

    return render(request, 'frontend/home.html', {
        "products": products,
    })


def filter_by_category(request, category_id):
    products = product_helpers.filter_by_category(request, category_id)
    attributes = Property.objects.filter(product__in=products).order_by(
        'name').values('name', 'description')
    attributes_temp = []
    lastName = ""
    for att in attributes:
        if att['name'] == lastName:
            attributes_temp.append(att)
        else:
            lastName = att['name']
            attributes_temp.append({'globalName': att['name']})
            attributes_temp.append(att)

    return render(request, 'frontend/home.html', {"products": products, 'propertiesCust': attributes_temp})


def product_info(request, product_id):
    product = product_helpers.detail(request, product_id)
    photos = product_helpers.product_photos(request, product_id)
    properties = product_helpers.get_all_product_properties(
        request, product_id)

    thumb_rows = []

    temp = 0
    # Thumbnail row to make
    chunks = math.ceil(len(photos)/4)

    for i in range(chunks):
        t = []
        for j in range(min(4, len(photos) - temp)):
            temp += 1

            t.append(photos[i * 4 + j])
        thumb_rows.append(t)

    data = {
        "product": product,
        "photos": photos,
        "thumb_rows": thumb_rows,
        "properties": properties
    }

    return render(request, 'frontend/components/product.html', data)


def faq(request):
    return render(request, 'frontend/faq.html')


def contact(request):
    return render(request, 'frontend/contact.html')


def about(request):
    return render(request, 'frontend/about.html')


def cart(request):
    cart_info = cart_helpers.test_request(request)
    return render(request, 'frontend/components/cart/index.html')


def auth_redirect(request):
    if request.user.is_authenticated:
        return redirect('/')

def signin(request):
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'GET':

        return render(request, 'frontend/signin.html')

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')


        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')

        else:
            data = {
                "message": {
                    "type": 'error-msg',
                    "content": "Invalid Credentials.. Try again!"
                }
            }
            return  render(request, 'frontend/signin.html', data)

def signup(request):
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == 'GET':
        return render(request, 'frontend/signup.html')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        confirmation = request.POST.get('confirmation')


        message = len_validator(username, 4, 50)
        message = len_validator(password, 4, 50)
        message = len_validator(confirmation, 4, 50)
        message = password_validator(password, confirmation)

        if message['content'] == "":
            message = unique_validator(lambda: User.objects.filter(username=username), "Username already exists!")
            if message['content'] == "":
                user = User.objects.create_user(username=username, password=password)
                print(user)
                message['type'] = "success-msg"
                message["content"] = "Successfully created!"

        if message['content'] != "":
            data = {
                "message" : message
            }

        return render(request, 'frontend/signup.html', data)

def sign_out(request):
    logout(request)
    return redirect('home')



def filter_by_props(request):
    print("sadddddddddddddddddddddddd")
    filtered = product_helpers.filter_by(request)
    print(len(filtered))
    return home(request, products=filtered)

eshop/products/views.py
from decimal import *

from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponse, QueryDict
from products.models import Product, Category, Property, ProductImage


# Create your views here.


def get_products(request):
    products = Product.objects.all()
    return products


def get_categories(request):
    return Category.objects.all()


def get_product_categories(request):
    pass


def detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return product


def product_photos(request, product_id):
    photos = ProductImage.objects.filter(product_id=product_id)
    return photos


def get_all_product_properties(request, product_id):
    properties = Property.objects.filter(product_id=product_id)
    return properties


def filter_by_category(request, category_id):
    categories = Category.objects.get(
        pk=category_id).get_descendants(include_self=True)

    product_list = Product.objects.filter(categories__in=categories)

    return product_list


def filter_by(request):
    try:
        minPrice = Decimal(request.GET['minPrice'])
    except:
        minPrice = 0
        print("Cannot convert")

    try:
        maxPrice = Decimal(request.GET['maxPrice'])
        if minPrice > maxPrice or minPrice < 0 or maxPrice < 0:
            raise Exception('Bad price')
    except:
        maxPrice = 10000000
        print("Cannot convert")

    values_s = dict(request.GET)
    l = []
    [l.extend(v) for k, v in values_s.items()]
    attributes = Property.objects.filter(
        name__in=values_s.keys(), description__in=l)
    product_list = Product.objects.filter(
        property__in=attributes, price__gte=minPrice, price__lte=maxPrice).distinct()

    return product_list
    # return render(request, 'products/allproducts.html', {
    #     'products': product_list,
    # })

def search_products(query):
    return Product.objects.filter(title__icontains=query)

eshop/frontend/templates/frontend/components/filterSide.html
<div class="cardx">
    <h1>Select Filters</h1>
    <hr />
    <form method="GET" action="/filter/">
        <div class="d-flex flex-column justify-content-around ">
            {% if propertiesCust %}
                {% for prop in propertiesCust %}
                    <div class="d-flex flex-row justify-content-between">
                        {% if prop.globalName %}
                            <div>
                                <label>{{prop.globalName}}:</label>
                            </div>
                        {% else %}
                            <div class="d-flex flex-row">
                                    <span class="check-input"><input   class="form-control" type="checkbox" name="{{prop.name}}" value="{{prop.description}}" id="prop-{{prop.pk}}" checked></span>
                                    <span>{{prop.description}}</span>
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
            {% else %}
                {% for prop in properties %}
                    <div class="d-flex flex-row justify-content-between" >
                    {% if prop.globalName %}
                        <div>
                            <label>{{prop.globalName}}:</label>
                        </div>
                    {% else %}
                        <div class="d-flex flex-row">
                                <span class="check-input"><input   id="prop-{{prop.pk}}" class="form-control" type="checkbox" name="{{prop.name}}" value="{{prop.description}}" checked></span>
                                <span>{{prop.description}}</span>
                        </div>
                    {% endif %}
                    </div>
                {% endfor %}
        {% endif %}
        </div>

        <hr/>
        <div class="filter-content">
            <div class="card-body">
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Min</label>
                        <input value="0" name="minPrice" type="number" class="form-control" id="inputEmail4" placeholder="$0" />
                    </div>
                    <div class="form-group col-md-6 text-right">
                        <label>Max</label>
                        <input  value="16500" name="maxPrice" type="number" class="form-control" placeholder="$1,0000" />
                    </div>
                </div>
            </div>
            <!-- card-body.// -->
        </div>

        <button class="btn btn-warning text-white update-prop-btn"  id="update-prop-btn" type="submit">Set Filters</button>
    </form>

</div>

eshop/frontend/templates/frontend/components/message-handler.html
{% if message %}
    <div class="message-box">
        <p class="{{message.type}}">{{message.content}}</p>
    </div>
{% endif %}

eshop/frontend/templates/frontend/components/product-pagination.html
     <div class="pagination">
          {% if products.has_previous %}
          <a class="pagination-action" href="?page=1">
            <i class="fa fa-angle-double-left" aria-hidden="true"></i>
          </a>
          <a
            class="pagination-action"
            href="?page={{ products.previous_page_number }}"
          >
            <i class="fa fa-angle-left" aria-hidden="true"></i>
          </a>
          {% endif %}

          <span class="pagination-current">{{ products.number }}</span>
          <span class="pagination-of">of</span>
          <span class="pagination-total"
            >{{ products.paginator.num_pages }}</span
          >

          {% if products.has_next %}
          <a
            class="pagination-action"
            href="?page={{ products.next_page_number }}"
          >
            <i class="fa fa-angle-right" aria-hidden="true"></i>
          </a>
          <a
            class="pagination-action"
            href="?page={{ products.paginator.num_pages }}"
          >
            <i class="fa fa-angle-double-right" aria-hidden="true"></i>
          </a>
          {% endif %}
        </div>

eshop/frontend/templates/frontend/components/product.html
{% extends "frontend/base.html" %} {% block content %}
<div class="product-detail container mt-4 text-left">
  <h1 class="product-detail__heading">{{product.title}}</h1>

  <div class="container p-4">
    <hr />
    <div class="row text-center">
      <div class="col-md-8">
        {% include "frontend/components/product-photos/preview-component.html" %}
      </div>
      <div class="col-md-4">
        {% include "frontend/components/product-photos/product-info.html" %}

        <div class="row">
          <div class="col">
            <button class="btn btn-warning add-to-cart-button" >Add To Cart</button>
          </div>
          <div class="col">
            <button class="btn btn-success buy-button">Buy</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

eshop/frontend/templates/frontend/components/products.html
{% if products %} {% for product in products %}
<div class="col-md-3">
  <figure class="card card-product">
    <a class="img-wrap" href="{% url 'product-view' product_id=product.id %}">
      {% if product.productimage_set.first %}
      <img src="{{ product.productimage_set.first.image.url }}" />
      {% else %}
      <img src="/media/other/default-image.png" />
      {% endif %}
    </a>
    <figcaption class="info-wrap">
      <h6 class="title text-dots">
        <a href="{% url 'product-view' product_id=product.id %}"
          >{{product.title}}</a
        >
      </h6>
      <div class="action-wrap">
        <a
          href="{% url 'product-view' product_id=product.id %}"
          class="btn btn-primary btn-sm float-right cart-logo"
        >
          <i class="fa fa-shopping-cart"></i>
        </a>
        <div class="price-wrap h5">
          <span class="price-new">{{product.price}}$</span>
          {% comment %} <del class="price-old">$1980</del> {% endcomment %}
        </div>
        <!-- price-wrap.// -->
      </div>
      <!-- action-wrap -->
    </figcaption>
  </figure>
  <!-- card // -->
</div>
{% endfor %} {% else %}
<p class="text-danger">Currently, there is no products for this category...</p>
{% endif %}